/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package Vistas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.toast.Notifications;

/**
 *
 * @author jhoax
 */
public class FormEditarClipping extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;

    /**
     * Creates new customizer FormEditarClipping
     */
    public FormEditarClipping(ET.ETemplate obj) throws IOException {
        initComponents();
        MostrarClipping(obj);
        FormInicio fi = new FormInicio();
        fi.VerificarCarpetas();
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    public void MostrarClipping(ET.ETemplate obj) throws IOException {

        BL.BLTemplate bltemp = new BL.BLTemplate();
        bltemp.MostrarTemp(obj);
        txtNombre.setText(obj.getNombre());
        textArea.setText(obj.getContenido());
        lblRuta.setText(obj.getArea());
        lblRuta.hide();
    }

    public void EditarClipping() throws IOException {

        String nombre = txtNombre.getText();
        String contenido = textArea.getText();
        String ruta = lblRuta.getText();

        ET.ETemplate etemp = new ET.ETemplate(nombre, true, contenido, ruta);

        BL.BLTemplate bltemp = new BL.BLTemplate();

        bltemp.EditarTemplate(etemp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textArea = new java.awt.TextArea();
        btnEditar = new javax.swing.JToggleButton();
        btnAyuda = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textArea.setBackground(new java.awt.Color(250, 250, 250));
        textArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        textArea.setName("agregue la información de su clipping"); // NOI18N
        textArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textAreaMouseEntered(evt);
            }
        });
        jPanel1.add(textArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 400, 240));

        btnEditar.setBackground(new java.awt.Color(204, 0, 51));
        btnEditar.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Save");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 70, 30));

        btnAyuda.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnAyuda.setText("Help");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 30));

        jSeparator3.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 220, 10));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 30));

        jLabel1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel1.setText("File Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        lblRuta.setText("jLabel2");
        jPanel1.add(lblRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void textAreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaMouseEntered

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Notifications.getInstance().show(Notifications.Type.INFO,
                Notifications.Location.TOP_CENTER, 9999999,
                "Hello! Here you can edit an existing file, \n"
                + " you must select the one you want to edit and specify the new information and finally press Edit.\n");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            EditarClipping();
            Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, "Successfully updated text");

        } catch (IOException ex) {
            Logger.getLogger(FormEditarClipping.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblRuta;
    private java.awt.TextArea textArea;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
