
package Vistas;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Font;
import java.io.File;
import raven.toast.Notifications;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FormCrearClipping extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;

    public FormCrearClipping() {
        initComponents();
        customizeComponents();
        addMouseListenerToTextPane();
        jLabel2.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h6.font");
        LlenarCbxArea();
                Font font = new Font("Arial", Font.PLAIN, 12);
        txtAreaTemplate.setFont(font);
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    public void GuardarTemplate() throws IOException {
       String nombre = inpNombre.getText();
        String contenido = txtAreaTemplate.getText();
        
        String homeDir = System.getProperty("user.home");
        String area = cbxArea.getSelectedItem().toString();
        String tipo = cbxTipo.getSelectedItem().toString();
        
        String ruta = homeDir + File.separator + "Downloads" + File.separator + "Clipping" + File.separator + "Archivos" + File.separator + "Activos" + File.separator + area + File.separator + tipo;
        
        ET.ETemplate etemp = new ET.ETemplate(nombre, true, contenido, ruta);
        
        BL.BLTemplate bltemp = new BL.BLTemplate();
        
        bltemp.GuardarTemplate(etemp);
    }

    public void LlenarCbxArea() {
       String homeDir = System.getProperty("user.home");
        String ruta = homeDir + File.separator + "Downloads" + File.separator + "Clipping" + File.separator + "Archivos" + File.separator + "Activos";
        
        BL.BLArea bla = new BL.BLArea();
        List<String> datos = new ArrayList<>();
        bla.CargarCombo(ruta, datos);
        
        cbxArea.removeAllItems();
        for (int i = 1; i < datos.size(); i++) {
            String dato = datos.get(i);
            cbxArea.addItem(dato);
        }
        LlenarCbxTipoC();
    }

    public void LlenarCbxTipoC() {
         String homeDir = System.getProperty("user.home");
        String area = cbxArea.getSelectedItem().toString();
        String ruta = homeDir + File.separator + "Downloads" + File.separator + "Clipping" + File.separator + "Archivos" + File.separator + "Activos" + File.separator + area;
        
        BL.BLTipoTemplate bltt = new BL.BLTipoTemplate();
        List<String> datos = new ArrayList<>();
        bltt.CargarCombo(ruta, datos);
        
        cbxTipo.removeAllItems();
        for (String dato : datos) {
            cbxTipo.addItem(dato);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAreaTemplate = new java.awt.TextArea();
        inpNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JToggleButton();
        btnAyuda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cbxArea = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaTemplate.setBackground(new java.awt.Color(250, 250, 250));
        txtAreaTemplate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAreaTemplate.setFont(new java.awt.Font("Arial", Font.PLAIN, 12));
        txtAreaTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAreaTemplateMouseEntered(evt);
            }
        });
        add(txtAreaTemplate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 430, 240));

        inpNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inpNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inpNombre.setToolTipText("Nombre del Archivo");
        inpNombre.setBorder(null);
        inpNombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        inpNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNombreActionPerformed(evt);
            }
        });
        add(inpNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 200, 30));

        jSeparator1.setForeground(new java.awt.Color(204, 0, 51));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, 10));

        jLabel1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 20));

        btnGuardar.setBackground(new java.awt.Color(204, 0, 51));
        btnGuardar.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Create");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, 30));

        btnAyuda.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        btnAyuda.setText("Help");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 30));

        jLabel2.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Information");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 20));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 0, 51));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 30));

        jLabel4.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Area");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 30));

        jSeparator3.setForeground(new java.awt.Color(204, 0, 51));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 10));

        cbxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        cbxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAreaActionPerformed(evt);
            }
        });
        add(cbxArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 30));

        jSeparator4.setForeground(new java.awt.Color(204, 0, 51));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, 10));

        jLabel5.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("File Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaTemplateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaTemplateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTemplateMouseEntered

    private void inpNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            GuardarTemplate();
            Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, 3000,"¡Saved Successfully!");
        } catch (IOException ex) {
            Logger.getLogger(FormCrearClipping.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Notifications.getInstance().show(Notifications.Type.INFO, Notifications.Location.TOP_CENTER, 9999999,
                "Hello! Here you can add a new file. To do so,\n"
                + "You need to put in a name and type in the information you want,\n"
                + "and finally, press Save.\n"
                + "\n"
                + "To add an editable field as a name to your text,\n"
                + "last name, etc., add the word in the text preceded by a\n"
                + "dollar sign, as shown in the example:\n"
                + "'Hi $name, how are you?...'\n"
                + "\n"
                + "I hope you're having a good day.");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void cbxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAreaActionPerformed
        LlenarCbxTipoC();
    }//GEN-LAST:event_cbxAreaActionPerformed

    private void customizeComponents() {
        txtAreaTemplate.setFont(new Font("Arial", Font.PLAIN, 16));
        txtAreaTemplate.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaTemplate.setBackground(new java.awt.Color(255, 255, 255));
        // Puedes agregar más configuraciones aquí
    }

    private void addMouseListenerToTextPane() {
        txtAreaTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyAdditionalProperties();
                drawNotebookLines();
            }
        });
    }

    private void applyAdditionalProperties() {
        // Puedes agregar aquí más propiedades o ajustes al textPane1
    }

    private void drawNotebookLines() {
        // Configura el borde del textPane1 para simular líneas como en un cuaderno
        //   textArea.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JComboBox<String> cbxArea;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JTextField inpNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private java.awt.TextArea txtAreaTemplate;
    // End of variables declaration//GEN-END:variables
}
