package Vistas;

import com.formdev.flatlaf.FlatClientProperties;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLayeredPane;
import javax.swing.JList;

public class FormAbout extends javax.swing.JPanel implements java.beans.Customizer {
    private JList<String> listaDirectorios;
    private DefaultListModel<String> listModel;
    private Object bean;
    private List<File> directorios;

    
    public FormAbout() {
        this.directorios = directorios;
        initComponents();
        //jLabel1.putClientProperty(FlatClientProperties.STYLE, ""
         //       + "font:$h1.font");
      
         // Inicializa la lista y el modelo
        listModel = new DefaultListModel<>();
        listaDirectorios = new JList<>(listModel);
      
    }
    
    
    
    public void updatePanelWithDirectories(List<File> directorios) {
        // Limpia el modelo antes de agregar los nuevos directorios
        listModel.clear();

        // Agrega los nombres de los directorios al modelo
        for (File directorio : directorios) {
            listModel.addElement(directorio.getName());
        }

        // Actualiza la vista de la lista
        listaDirectorios.updateUI();

        // ... Puedes agregar más lógica según tus necesidades ...
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel1.setText(" \"Do not be overcome by evil, but overcome evil with good.\" Romans 12:21");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 500, 45));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel2.setText("- José Emanuel Torres & Jhonmar Arguello ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 290, 39));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel4.setText("Intership Project maded by Students of COVAO.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 42, 500, 45));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setText("developed it for the  management and use of pre-designed notes, ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 534, 45));

        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 269, -1, -1));

        jLabel7.setText("jLabel7");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 269, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel8.setText("made in Java, in November 2023.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 534, 39));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
